# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'swift-boilerplate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for swift-boilerplate
  pod 'DateToolsSwift'
  pod 'SVProgressHUD'

  target 'swift-boilerplateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift-boilerplateUITests' do
    # Pods for testing
  end

end
